CREATE TABLE IF NOT EXISTS sharepoint_file_queue (
    id INT AUTO_INCREMENT PRIMARY KEY,
    drive_id VARCHAR(255) NULL,
    item_id VARCHAR(255) NOT NULL,
    source_folder VARCHAR(255) NOT NULL,
    processed_folder VARCHAR(255) NOT NULL,
    file_name VARCHAR(512) NOT NULL,
    sharepoint_size BIGINT NULL,
    sharepoint_etag VARCHAR(255) NULL,
    sharepoint_last_modified_at DATETIME NULL,
    local_path VARCHAR(1024) NULL,
    local_sha256 CHAR(64) NULL,
    status VARCHAR(40) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    next_retry_at DATETIME NULL,
    downloaded_at DATETIME NULL,
    moved_at DATETIME NULL,
    import_started_at DATETIME NULL,
    imported_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_sharepoint_file_queue_item_id (item_id),
    KEY idx_sharepoint_file_queue_status_modified (status, sharepoint_last_modified_at),
    KEY idx_sharepoint_file_queue_sha256 (local_sha256)
);
